services:
  app:
    env_file:
      - config/development/dev.env
    build: .
    image: my-ecommerce-app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: ["/usr/wait-for-it.sh", "db:5432", "--", "npm", "run", "dev"]

  db:
    env_file:
      - config/development/dev.env
    image: postgres:16.0-alpine3.17
    volumes:
      - ./ecommerce-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    env_file:
      - config/development/dev.env
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - db
