name: Node.js CI

on:
  push:
  pull_request:
    branches:
      - "develop"
    types: [opened, synchronize]

concurrency:
  group: Node.js CI
  cancel-in-progress: true

jobs:
  Test:
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.5.1]

    steps:
      - name: Checks out the repository code into the runner
        uses: actions/checkout@v4

      - name: Setup node environment
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm run test:ci
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DIALECT: ${{ secrets.DB_DIALECT }}

  deploy:
    name: Deploy
    needs: [Test]
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [20.5.1]

    steps:
      - name: Deploy
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.API_KEY }}
